import { useState } from 'react';
import { Save, X } from 'lucide-react';
import Field from '../../components/common/Field.jsx';
import { Input, Textarea, Select, Checkbox } from '../../components/common/Input.jsx';
import Button from '../../components/common/Button.jsx';
import MediaUploadField from '../../components/common/MediaUploadField.jsx';
import { uploadImage } from '../../api/uploads.js';

const blank = {
  title: '',
  excerpt: '',
  coverImage: '',
  category: '',
  author: 'Tirtha Yatri Team',
  tags: '',
  content: '',
  published: false,
  isFeatured: false,
};

// Client-side-only preview of the slug the server will generate from the
// title — never sent to the API, purely so the admin can see what to expect.
function slugPreview(title) {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export default function BlogForm({ initial, categories, onCancel, onSubmit, saving }) {
  const [form, setForm] = useState(() =>
    initial ? { ...blank, ...initial, tags: (initial.tags || []).join(', ') } : blank
  );
  const set = (key, value) => setForm((f) => ({ ...f, [key]: value }));

  function handleSubmit(e) {
    e.preventDefault();
    const payload = {
      ...form,
      tags: form.tags
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean),
    };
    onSubmit(payload);
  }

  return (
    <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
      <Field label="Title" required>
        <Input value={form.title} onChange={(e) => set('title', e.target.value)} required />
      </Field>

      <Field label="Slug preview (auto-generated)" hint="Generated by the server from the title when you save — shown here for reference only.">
        <Input value={slugPreview(form.title)} disabled />
      </Field>

      <Field label="Excerpt" required hint="Used as the card and SEO description — keep it short, around 200–280 characters.">
        <Textarea rows={3} maxLength={280} value={form.excerpt} onChange={(e) => set('excerpt', e.target.value)} required />
      </Field>

      <Field label="Cover Image" required hint="Upload a file, or paste/edit an image URL directly.">
        <MediaUploadField
          value={form.coverImage}
          onChange={(v) => set('coverImage', v)}
          uploadFn={uploadImage}
          accept="image/jpeg,image/png,image/webp,image/gif"
          preview="image"
        />
      </Field>

      <Field label="Category" required>
        <Select value={form.category} onChange={(e) => set('category', e.target.value)} required>
          <option value="">Select category…</option>
          {categories.map((c) => (
            <option key={c._id} value={c.slug}>
              {c.name}
            </option>
          ))}
        </Select>
      </Field>

      <Field label="Author">
        <Input value={form.author} onChange={(e) => set('author', e.target.value)} />
      </Field>

      <Field label="Tags" hint="Comma-separated, e.g. Mustang, Trekking, Guide">
        <Input value={form.tags} onChange={(e) => set('tags', e.target.value)} />
      </Field>

      <Field
        label="Content"
        required
        hint={
          'Supports Markdown: # Heading, **bold**, *italic*, - list item, > quote, ![alt](url "caption"), [link text](url). Leave a blank line between paragraphs.'
        }
      >
        <Textarea rows={14} value={form.content} onChange={(e) => set('content', e.target.value)} required />
      </Field>

      <div style={{ display: 'flex', gap: '1.5rem' }}>
        <Checkbox label="Publish immediately" checked={form.published} onChange={(e) => set('published', e.target.checked)} />
        <Checkbox label="Featured" checked={form.isFeatured} onChange={(e) => set('isFeatured', e.target.checked)} />
      </div>

      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
        <Button type="button" variant="outline" icon={X} onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit" icon={Save} disabled={saving}>
          {saving ? 'Saving…' : 'Save'}
        </Button>
      </div>
    </form>
  );
}
